# Generated by Django 3.0.2 on 2020-01-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200123_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите разряд публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю')], default='', max_length=1),
        ),
    ]
